name: Build VCFengine.exe

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  windows-vcf-engine:
    name: Windows-x64-VCFengine
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Rapfi
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            make
            git

      - name: Build VCFengine.exe
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_VCF_ENGINE=ON \
            -DNO_COMMAND_MODULES=ON \
            -DUSE_SSE=ON \
            -DUSE_AVX2=ON \
            -DUSE_AVX512=OFF \
            -DUSE_BMI2=OFF \
            -DUSE_VNNI=OFF
          cmake --build . -j2
          strip VCFengine.exe

      - name: Upload VCFengine.exe
        uses: actions/upload-artifact@v4
        with:
          name: VCFengine-Windows-x64
          path: Rapfi/build/VCFengine.exe
          if-no-files-found: error
